### ISSUE TITLE
It stops working after a couple mins

### ISSUE THREAD

**Issue by Runewiz** [JesseVii/TTS#27] opened 2023-06-24 05:54 UTC
This is the biggest issue and needs to be addressed. Would be awesome if it worked through the duration of a session.

**Comment by wanieru** [comment] 2023-09-16 15:04
I noticed the recently added "AltTool"-field in the plugin, and I can see from the source code that if it contains the text "Brian5" and the chosen voice is Susan, it uses a different function and source for the TTS, and this version doesn't have the issue of the TTS stopping working after a while (or the other issue I've been experiencing, with the game freezing before each line of dialogue). Unfortunately it currently always uses the same voice called "Brian".

**Comment by iProdigy** [comment] 2024-02-26 09:50
Duplicate of #26

**Closed** 2024-03-02 21:17 UTC
